generate_dockerfile:
  image: julia:latest
  stage: .pre
  only:
    changes:
      - scripts/container_generator.jl
  script:
    - julia -e 'using Pkg; Pkg.add("SimpleContainerGenerator")'
    - julia scripts/container_generator.jl
  artifacts:
    paths:
      - container

build_and_push_image:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  needs:
    - job: generate_dockerfile
      artifacts: true
  only:
    changes:
      - scripts/container_generator.jl
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  script:
    - export DATE=$(date +'%Y%m%d')
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker buildx build -t $IMAGE_TAG:$DATE -t $IMAGE_TAG:latest container/
    - docker push -a $IMAGE_TAG